export const pageBackgroundColor = '#efefef';
export const tabBarborderColor = '#e9e9e9';
export const tabSelectedColor = '#ffae00';
export const tabNormalColor = '#000000';
export const blockColor = '#fff';
export const disableTextColor = '#999999';
export const lineBackgroundColor = '#2196f3';
export const warnColor = '#f7453b';
//# sourceMappingURL=color.js.map